# Generated by Django 5.1 on 2024-09-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gamehistory_userstats_delete_gamedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='game_history',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
