# Generated by Django 5.1 on 2024-09-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='game_history',
        ),
    ]
