# Generated by Django 5.1 on 2024-09-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gamehistory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='games',
            new_name='game',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='avg_game_throw',
            field=models.FloatField(default=0),
        ),
    ]
