# Generated by Django 5.1 on 2024-09-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_games_gamehistory_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehistory',
            name='total_turns',
            field=models.IntegerField(default=0),
        ),
    ]
