# Generated by Django 5.1 on 2024-09-04 23:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userstats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='played_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
