# Generated by Django 5.1 on 2024-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gamehistory_played_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='avg_leg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='avg_leg',
            field=models.FloatField(default=0.0),
        ),
    ]
